# Generated by Django 2.2 on 2019-04-13 12:33

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='media/party_place')),
                ('description', models.TextField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('attenders', models.ManyToManyField(related_name='attenders', to='member.Xmember')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to='member.Xmember')),
            ],
        ),
    ]
