# Generated by Django 2.2 on 2019-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
